version: 0.2

phases:
  install:
    commands:
      - echo Verificando versoes do dotnet...
      - dotnet --list-sdks
  pre_build:
    commands:
      - echo Fazendo login no Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Iniciando o Build em `date`
      - echo Compilando o projeto .NET...
      - dotnet publish -c Release -o out/
      - echo Criando Dockerfile...
      - |
        cat <<EOF > Dockerfile
        FROM mcr.microsoft.com/dotnet/aspnet:6.0
        WORKDIR /app
        COPY out/ .
        EXPOSE 80
        ENTRYPOINT ["dotnet", "MeuSite.dll"]
        EOF
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build finalizado em `date`
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:latest" > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
